server:
  port: 9999

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql:///springboot?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.cskj.goodsdome.bean

logging:
  level:
    org.cskj.goodsdome.mapper : debug